services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "18081:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/your_database
      - SPRING_DATASOURCE_USERNAME=your_user
      - SPRING_DATASOURCE_PASSWORD=your_password
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "15432:5432"   # 15432 — внешний порт на локальной машине
                       # 5432 — внутренний порт внутри контейнера
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db-data: